#12 Cadastro de proposta
fga-eps-mds/2021-1-PUMA-Frontend pull request #4
Opened 2021-10-13 20:49 UTC by LeviQ27

Relacionada a Issue #12

## O que faz?

Acrescenta a interface visualização do cadastro de propostas

## Como validar?
Com todos os repositórios baixados, trocar a branch dos repos:

2021-1-PUMA-Frontend -> 12-cadastro-proposta
2021-1-PUMA-ProjectService -> 12-cadastro-proposta
2021-1-PUMA-ApiGateway -> 12-cadastro-proposta
* Rodar o projeto e realizar cadastro/login
* É importante popular o banco da área de conhecimento com:
    -  Com algumas knowledgearea ids
    - Com user de id 1 e com o subject de id 1
    - Upload limitado a 1 mB 
* Cadastrar uma proposta com o envio de um arquivo pequeno

## Problemas conhecidos

* Ainda faltam os testes unitários

### Issues relacionadas

Closes #4

2021-10-15 00:52 UTC, LhTaira requested changes

2021-10-15 02:05 UTC, LhTaira requested changes
![image](https://user-images.githubusercontent.com/34405790/137420803-221697fc-1358-4f72-bfbd-f105a45188b4.png)

Aparecem dois cursores no campo de cadastro

2021-10-15 02:20 UTC, LhTaira requested changes
![image](https://user-images.githubusercontent.com/34405790/137422010-f346f52f-6441-4fac-a822-bf35c8f13319.png)


Mesmo quando existe knowlegde area cadastrada no banco não é possível cadastrar proposta

2021-10-15 02:33 UTC, LhTaira requested changes

2021-10-15 02:40 UTC, LhTaira requested changes

2021-10-16 00:18 UTC, LhTaira requested changes
esquece esse comentário

2021-10-17 16:50 UTC, jpmartins201 commented
> * A tela de registro de proposta está quebrando quando qualquer outra opção da navbar é selecionada
> * Tem um typo na navbar "Cadastro e projeto", além de estar colado com os outros botões
>   ![image](https://user-images.githubusercontent.com/38573077/137383983-f8a576e1-8d1e-49fb-bcb1-4386d63718b0.png)

Typo resolvido e o bug do css resolvido trocando o `<router-link>` por `<a>` com a rota dos componentes da navbar.

2021-10-21 14:41 UTC, LhTaira requested changes
![image](https://user-images.githubusercontent.com/34405790/138301056-4a0c1f18-520b-4949-a404-a0ca7e41f81c.png)

O login e cadastro estão quebrados

![image](https://user-images.githubusercontent.com/34405790/138301145-210b2360-1ea7-437e-a930-3e2cb526b3e1.png)


O cadastro de proposta tem que estar de acordo com o protótipo

2021-10-21 14:51 UTC, LhTaira requested changes
![image](https://user-images.githubusercontent.com/34405790/138303035-e1f917dd-44c2-498e-bae7-6695ecf2db6f.png)

Não deu certo o cadastro de proposta

2021-10-29 21:26 UTC, LhTaira requested changes
![image](https://user-images.githubusercontent.com/34405790/139503507-d8d7334c-7e97-4c3f-9944-b67296bc25c6.png)

![image](https://user-images.githubusercontent.com/34405790/139503612-3141d3ff-1b60-4f71-b2a0-330bb816c27f.png)

2021-10-29 21:45 UTC, LhTaira requested changes
![image](https://user-images.githubusercontent.com/34405790/139505095-70aa9578-cb1b-437c-860b-4643cd9b9508.png)

Ta bizarro

2021-11-02 04:57 UTC, closed without merging